Upgrade
YunoHost-Apps/galene_ynh pull request #93
Opened 2022-10-04 22:37 UTC by yalh76

## Problem

- *Description of why you made this PR*

## Solution

- *Implement LDAP authentication*
- *Apply last example_ynh*
- *Tweak the group page*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-10-04 22:45 UTC, yalh76 commented
!testme

2022-10-05 00:05 UTC, yalh76 commented
!testme

2022-10-05 00:43 UTC, yalh76 commented
!testme

2022-10-05 10:17 UTC, ericgaspar requested changes

2022-10-05 10:17 UTC, ericgaspar commented on conf/groupname-ldap.json
> + 	"description": "Group of YunoHost users",
```suggestion
 	"description": "YunoHost User Group",
```

2022-10-05 10:17 UTC, ericgaspar commented on scripts/install
> +	ynh_exec_as $app CGO_ENABLED=0 $ynh_go build -ldflags='-s -w' -o $final_path/live/
```suggestion
	ynh_exec_warn_less ynh_exec_as $app CGO_ENABLED=0 $ynh_go build -ldflags='-s -w' -o $final_path/live/
```

2022-10-05 10:17 UTC, ericgaspar commented on scripts/install
> +	ynh_exec_as $app CGO_ENABLED=0 $ynh_go build -ldflags='-s -w' -o $final_path/live_ldap/
```suggestion
	ynh_exec_warn_less ynh_exec_as $app CGO_ENABLED=0 $ynh_go build -ldflags='-s -w' -o $final_path/live_ldap/
```

2022-10-05 10:17 UTC, ericgaspar commented on scripts/install
> +	ynh_exec_as $app CGO_ENABLED=0 $ynh_go build -ldflags='-s -w' -o $final_path/live_ldap/
let's try to get rid of all the warnings

2022-10-05 18:31 UTC, yalh76 commented
!testme

2022-10-05 19:12 UTC, yalh76 commented
oupsi, I forgot to manage upgrade from current version

2022-10-05 19:39 UTC, yalh76 commented
!testme

2022-10-05 20:19 UTC, ericgaspar approved these changes
Thanks for improving the package!

2022-10-05 20:23 UTC, merged